const categories = [
    {
        "label": "Общение с друзьями",
        "value": "CommunicatingWithFriends",
        "words": [
            {"en": "friend", "it": "amico/amica", "ru": "друг/подруга"},
            {"en": "party", "it": "festa", "ru": "вечеринка"},
            {"en": "chat", "it": "chiacchierata", "ru": "беседа"},
            {"en": "call", "it": "chiamata", "ru": "звонок"},
            {"en": "joke", "it": "scherzo", "ru": "шутка"},
            {"en": "hang out", "it": "uscire", "ru": "тусоваться"},
            {"en": "invite", "it": "invitare", "ru": "приглашать"},
            {"en": "meet", "it": "incontrare", "ru": "встречаться"},
            {"en": "play", "it": "giocare", "ru": "играть"},
            {"en": "fun", "it": "divertimento", "ru": "веселье"},
            {"en": "laugh", "it": "ridere", "ru": "смеяться"},
            {"en": "share", "it": "condividere", "ru": "делиться"},
            {"en": "secret", "it": "segreto", "ru": "секрет"},
            {"en": "support", "it": "sostenere", "ru": "поддерживать"},
            {"en": "memory", "it": "memoria", "ru": "воспоминание"},
            {"en": "hug", "it": "abbraccio", "ru": "обнимать"},
            {"en": "trust", "it": "fiducia", "ru": "доверие"},
            {"en": "talk", "it": "parlare", "ru": "говорить"},
            {"en": "plan", "it": "pianificare", "ru": "планировать"},
            {"en": "celebrate", "it": "celebrare", "ru": "праздновать"}
        ]
    },
    {
        "label": "Встреча",
        "value": "Meeting",
        "words": [
            {"en": "meet", "it": "incontrare", "ru": "встречаться"},
            {"en": "introduce", "it": "presentare", "ru": "представлять"},
            {"en": "name", "it": "nome", "ru": "имя"},
            {"en": "handshake", "it": "stretta di mano", "ru": "рукопожатие"},
            {"en": "greet", "it": "salutare", "ru": "приветствовать"},
            {"en": "smile", "it": "sorridere", "ru": "улыбаться"},
            {"en": "talk", "it": "parlare", "ru": "говорить"},
            {"en": "conversation", "it": "conversazione", "ru": "разговор"},
            {"en": "ask", "it": "chiedere", "ru": "спрашивать"},
            {"en": "answer", "it": "rispondere", "ru": "отвечать"},
            {"en": "question", "it": "domanda", "ru": "вопрос"},
            {"en": "hobby", "it": "passatempo", "ru": "хобби"},
            {"en": "job", "it": "lavoro", "ru": "работа"},
            {"en": "interest", "it": "interesse", "ru": "интерес"},
            {"en": "where", "it": "dove", "ru": "где"},
            {"en": "how", "it": "come", "ru": "как"},
            {"en": "when", "it": "quando", "ru": "когда"},
            {"en": "why", "it": "perché", "ru": "почему"},
            {"en": "goodbye", "it": "arrivederci", "ru": "до свидания"},
            {"en": "nice to meet you", "it": "piacere di conoscerti", "ru": "приятно познакомиться"}
        ]
    },
    {
        "label": "В супермаркете",
        "value": "AtTheSupermarket",
        "words": [
            {"en": "buy", "it": "comprare", "ru": "покупать"},
            {"en": "cart", "it": "carrello", "ru": "тележка"},
            {"en": "checkout", "it": "cassa", "ru": "касса"},
            {"en": "cashier", "it": "cassiere", "ru": "кассир"},
            {"en": "price", "it": "prezzo", "ru": "цена"},
            {"en": "discount", "it": "sconto", "ru": "скидка"},
            {"en": "receipt", "it": "scontrino", "ru": "чек"},
            {"en": "bag", "it": "borsa", "ru": "сумка"},
            {"en": "produce", "it": "prodotti freschi", "ru": "продукты"},
            {"en": "aisle", "it": "corsia", "ru": "проход"},
            {"en": "shelf", "it": "scaffale", "ru": "полка"},
            {"en": "item", "it": "articolo", "ru": "товар"},
            {"en": "quantity", "it": "quantità", "ru": "количество"},
            {"en": "fresh", "it": "fresco", "ru": "свежий"},
            {"en": "frozen", "it": "congelato", "ru": "замороженный"},
            {"en": "dairy", "it": "latticini", "ru": "молочные продукты"},
            {"en": "bread", "it": "pane", "ru": "хлеб"},
            {"en": "vegetables", "it": "verdure", "ru": "овощи"},
            {"en": "fruits", "it": "frutta", "ru": "фрукты"},
            {"en": "checkout line", "it": "fila alla cassa", "ru": "очередь на кассе"}
        ]
    },
    {
        "label": "На отдыхе",
        "value": "OnHoliday",
        "words": [
            {"en": "relax", "it": "rilassarsi", "ru": "расслабляться"},
            {"en": "beach", "it": "spiaggia", "ru": "пляж"},
            {"en": "sun", "it": "sole", "ru": "солнце"},
            {"en": "swim", "it": "nuotare", "ru": "плавать"},
            {"en": "hotel", "it": "albergo", "ru": "отель"},
            {"en": "resort", "it": "villaggio turistico", "ru": "курорт"},
            {"en": "pool", "it": "piscina", "ru": "бассейн"},
            {"en": "tour", "it": "tour", "ru": "экскурсия"},
            {"en": "sightseeing", "it": "visita turistica", "ru": "осмотр достопримечательностей"},
            {"en": "adventure", "it": "avventura", "ru": "приключение"},
            {"en": "relaxation", "it": "rilassamento", "ru": "расслабление"},
            {"en": "spa", "it": "spa", "ru": "спа"},
            {"en": "souvenir", "it": "souvenir", "ru": "сувенир"},
            {"en": "flight", "it": "volo", "ru": "рейс"},
            {"en": "explore", "it": "esplorare", "ru": "исследовать"},
            {"en": "enjoy", "it": "godere", "ru": "наслаждаться"},
            {"en": "vacation", "it": "vacanza", "ru": "отпуск"},
            {"en": "journey", "it": "viaggio", "ru": "путешествие"},
            {"en": "trip", "it": "gita", "ru": "поездка"},
            {"en": "relaxing", "it": "rilassante", "ru": "расслабляющий"}
        ]
    },
    {
        "label": "В путешествии",
        "value": "Traveling",
        "words": [
            {"en": "travel", "it": "viaggiare", "ru": "путешествовать"},
            {"en": "passport", "it": "passaporto", "ru": "паспорт"},
            {"en": "luggage", "it": "bagaglio", "ru": "багаж"},
            {"en": "flight", "it": "volo", "ru": "рейс"},
            {"en": "airport", "it": "aeroporto", "ru": "аэропорт"},
            {"en": "ticket", "it": "biglietto", "ru": "билет"},
            {"en": "check-in", "it": "check-in", "ru": "регистрация"},
            {"en": "departure", "it": "partenza", "ru": "отправление"},
            {"en": "arrival", "it": "arrivo", "ru": "прибытие"},
            {"en": "destination", "it": "destinazione", "ru": "пункт назначения"},
            {"en": "tourist", "it": "turista", "ru": "турист"},
            {"en": "guide", "it": "guida", "ru": "гид"},
            {"en": "map", "it": "mappa", "ru": "карта"},
            {"en": "adventure", "it": "avventura", "ru": "приключение"},
            {"en": "explore", "it": "esplorare", "ru": "исследовать"},
            {"en": "route", "it": "percorso", "ru": "маршрут"},
            {"en": "journey", "it": "viaggio", "ru": "путешествие"},
            {"en": "train", "it": "treno", "ru": "поезд"},
            {"en": "bus", "it": "autobus", "ru": "автобус"},
            {"en": "hotel", "it": "albergo", "ru": "отель"}
        ]
    },
    {
        "label": "Водителю",
        "value": "ToTheDriver",
        "words": [
            {"en": "drive", "it": "guidare", "ru": "водить"},
            {"en": "car", "it": "auto", "ru": "машина"},
            {"en": "road", "it": "strada", "ru": "дорога"},
            {"en": "traffic", "it": "traffico", "ru": "движение"},
            {"en": "signal", "it": "segnale", "ru": "сигнал"},
            {"en": "stop", "it": "fermare", "ru": "остановить"},
            {"en": "go", "it": "andare", "ru": "ехать"},
            {"en": "speed", "it": "velocità", "ru": "скорость"},
            {"en": "limit", "it": "limite", "ru": "предел"},
            {"en": "highway", "it": "autostrada", "ru": "шоссе"},
            {"en": "direction", "it": "direzione", "ru": "направление"},
            {"en": "turn", "it": "girare", "ru": "поворачивать"},
            {"en": "left", "it": "sinistra", "ru": "налево"},
            {"en": "right", "it": "destra", "ru": "направо"},
            {"en": "straight", "it": "dritto", "ru": "прямо"},
            {"en": "destination", "it": "destinazione", "ru": "пункт назначения"},
            {"en": "fuel", "it": "carburante", "ru": "топливо"},
            {"en": "engine", "it": "motore", "ru": "двигатель"},
            {"en": "park", "it": "parcheggiare", "ru": "парковаться"},
            {"en": "license", "it": "patente", "ru": "лицензия"}
        ]
    }
];

export default categories;
